import fs from "fs/promises";
import path from "path";

const DOCS_ROOT = path.resolve(process.cwd(), "docs-cache", "docs");

// Validate path is within DOCS_ROOT
function validatePath(filePath: string): void {
  const normalizedPath = path.normalize(filePath);
  if (!normalizedPath.startsWith(DOCS_ROOT)) {
    throw new Error('Invalid path: Attempted path traversal');
  }
}

// Sanitizer to remove Fumadocs JSX comment
function sanitizeContent(content: string): string {
  return content.replace(
    /\{\/\*[^*]*This file was generated by Fumadocs[^*]*\*\/\}/g,
    "",
  );
}

export async function getLocalDocFile(file: string): Promise<string> {
  // Remove double .md/.mdx extensions if present
  file = file.replace(/\.(md|mdx)\.(md|mdx)$/i, ".$1");
  const filePath = path.join(DOCS_ROOT, file);
  validatePath(filePath);
  
  let content: string | undefined;
  let triedMdx = false;
  try {
    content = await fs.readFile(filePath, "utf8");
  } catch (e: any) {
    // Try .mdx if .md not found
    if (file.endsWith('.md')) {
      const mdxFile = file.replace(/\.md$/, '.mdx');
      const mdxPath = path.join(DOCS_ROOT, mdxFile);
      validatePath(mdxPath);
      try {
        content = await fs.readFile(mdxPath, "utf8");
        triedMdx = true;
      } catch (e2: any) {
        throw new Error(`Local doc not found: ${file}`);
      }
    } else {
      throw new Error(`Local doc not found: ${file}`);
    }
  }
  if (!content!.startsWith("---")) {
    const title = path.basename(file, path.extname(file));
    // Remove top-level markdown title ONLY if it matches the folder name
    const parentDir = path.basename(path.dirname(file));
    const titleRegex = new RegExp(
      `^#\\s+${parentDir.replace(/[-_.]/g, "[ -_.]")}\\s*\\n+`,
      "i",
    );
    if (title.toLowerCase() === parentDir.toLowerCase()) {
      content = content!.replace(titleRegex, "");
    }
    content = `---\ntitle: ${title}\ndescription: \n---\n\n` + content;
  }
  // Sanitize content to remove Fumadocs comment
  content = sanitizeContent(content!);
  return content!;
}

export async function listLocalDocs(
  dir = "",
): Promise<{ name: string; path: string; type: "file" | "dir" }[]> {
  const absDir = path.join(DOCS_ROOT, dir);
  let entries: any[] = [];
  try {
    entries = await fs.readdir(absDir, { withFileTypes: true });
  } catch (e: any) {
    throw new Error(`Local docs directory not found: ${dir}`);
  }
  // Exclude meta.json and openapi.json
  return entries
    .filter((entry) => !["meta.json", "openapi.json"].includes(entry.name))
    .map((entry) => ({
      name: entry.name,
      path: path.join(dir, entry.name).replace(/\\/g, "/"),
      type: entry.isDirectory() ? "dir" : "file",
    }));
}
